### ISSUE TITLE
Not asked for permission to access camera or mic --> failed to access

### ISSUE THREAD

**Issue by coach1988** [jitsi/jitsi-meet-electron#333] opened 2020-05-12 21:57 UTC
Hello there, first of all thank you so much for all your hard work, we really appreciate it in our company, as jitsi is so easy to use that it got adapted really quick by almost everyone.
After using jitsi primarily via rocketchat, i've started deploying the electron app to allow screen control, as it has been requested many times and i've found out (only by accident, you should really make that a bit more of a obvious thing, it's great) that jitsi can do it, if the the electron version is used.
some users (with webcam, that's a difference between them and working clients) have reported that the program only shows an error that access to the camera and microphone wasn't granted, without being asked for it at all, so no way for them to fix it:

![Clipboard - May 12, 2020 5 59 PM](https://user-images.githubusercontent.com/2565989/81749859-6f277800-947a-11ea-9009-3bfcc8e1bb55.png)

There are no problems when using the browser.
The affected clients are running Windows 10 1909 and version 2.0.2 of the app, windows app privacy settings for camera and microphone have been checked.
The jitsi integration of the rocketchat electron app works though.

Please let me know how/where to gather further information (logs, registry, config edits, etc.) and i will happily try to provide everything as good as i can:)

Thank you very much and keep up this excellent work, you are making a huge difference for admins like me (just take a look at reddit regarding jitsi), especially during these times.

**Comment by saghul** [comment] 2020-05-20 19:42
So this only happened to users who did have a webcam?

**Comment by coach1988** [comment] 2020-05-20 20:30
@saghul 
Yes, as far as i can tell, had some other users without cam testing it without problems.

**Comment by saghul** [comment] 2020-05-20 20:35
2.1.0 just got released with a new Electron version, which also updated the builtin Chromium version. Can you please give it a try?

**Comment by coach1988** [comment] 2020-05-20 20:57
Already deploying it to the first testers, as i saw the fixes regarding this topic for mac os=)

**Comment by coach1988** [comment] 2020-05-21 16:00
@saghul OK, personally tested it with the new version on an affected device, same effect. However, I have created a backup of the %appdata% folder afterwards. I didn't see anything in the logs, but maybe there is something else I should look at (cookies, config.json, etc.), I'm just not uploading it as it may contain information about the user, cookies, etc, but if you need something specific, I'll check it/upload it (if it doesn't contain sensitive data).

The cmd output was not really interesting:
11:48:13.063 > Checking for update
11:48:13.586 > Generated new staging user ID: aaafc72f-cb58-5f22-bad5-b6a0d558044d
11:48:16.027 > Update for version 2.1.0 is not available (latest version: 2.1.0, downgrade is disallowed).
11:48:16.032 > checkForUpdatesAndNotify called, downloadPromise is null

**Comment by saghul** [comment] 2020-05-21 16:23
Hum. I’ll dust off my windows laptop to give it a try.

**Comment by coach1988** [comment] 2020-05-22 19:51
I will play around with our AV system,wouldn't be the first time that creates issues (though I have little hope about that,as the rocketchat app worked without any further configuration changes). I'll keep you updated.

**Comment by saghul** [comment] 2020-05-23 16:29
I just tried it on an up to date Windows 10 machine (fresh Jitsi Meet install) and couldn’t reproduce the issue.

**Comment by coach1988** [comment] 2020-05-26 20:53
@saghul 
OK, I couldn't recreate the issue here with an "emulated" webcam (OBS VirtualCam, https://obsproject.com/forum/resources/obs-virtualcam.949/), but I'll try to get my hands on a real unit that is not a customized admin PC to test it under real conditions. I'll let you know in case I found something.

**Comment by coach1988** [comment] 2020-06-12 13:10
@saghul OK, it started working yesterday for one of the affected employees, he unfortunately upgraded to Windows 10 2004 shortly before though, so I can't say if it was the Jitsi update to 2.2.0 or the windows update, but I'll try to get that information from someone else for you, just to get this documented (as it seems to be solved now).

**Comment by saghul** [comment] 2020-06-12 13:43
Thanks for sharing! I'm going to tentatively close this then. If the issue reappears, drop a comment and we'll reopen.

**Closed** 2020-06-12 13:44 UTC
Labels: windows

**Comment by jrie** [comment] 2020-06-14 06:32
I encounter that permissions are not asked for and I cannot set anything from inside the settings as nothing is offered.

In the dropdowns there is only written "Permissions are not granted" ("Berechtigungen nicht erteilt") - and clicking on it does nothing. I would expect that I either can grant the permission or the ability to select the headset.

Once opening jitsi I only encounter the notice "The microphone cannot be accessed due to unknown reasons". Only if I connect a usb camera the "devices" panel in setting updates and I am able to select the camera and the audio output device. But I cannot set a microphone and the "Permssions are not granted" stays.

I am using the latest version 2.2.0 - Debian Sid without a webcam (usually) and a Razer Kraken Ultimate headset connected via USB which has a microphone.

**Comment by coach1988** [comment] 2020-06-16 16:41
@jrie It sounds a bit different than what i was encountering, as the affected users over here never saw dropdowns to chose from (see screenshot of first post), but it looks like the presence of a webcam has quite an impact on the further logic regarding audio devices.

@saghul Perhaps that could be of interest for you=)
