### ISSUE TITLE
No indication on mac when screenshare permission denied 

### ISSUE THREAD

**Issue by aslam-t** [jitsi/jitsi-meet-electron#940] opened 2024-01-11 23:11 UTC
## Description
In the latest Jitsi Meet Electron app [v2023.11.3](https://github.com/jitsi/jitsi-meet-electron/tree/v2023.11.3) on macOS Ventura if a user mistakenly deny the screen share permission dialog, the app make no additional permission request nor show any visual indication in call view to notify user about their lack of permission even if restarted. 

## Current behavior
For a user without system permissions to share the screen, no visual indication is shown for lack of permission. User still can share but others see a black screen feed on their sides.

## Expected Behavior
For a user without system permissions, show permission dialog again if possible or hide/disable the screen-share button and show some error banner/tootip to inform user to explicitly permit this app in settings.

## Possible Solution
---

## Steps to reproduce

1. Install Jitsi Meet Electron app
2. Create or join a conference
3. Press screenshare icon
4. Deny the permission dialog
5. Select "Entire Screen" or "Window" to share.

# Environment details
macOS Ventura 13.5.1 (22G90)
Jitsi Meet Electron [v2023.11.3](https://github.com/jitsi/jitsi-meet-electron/tree/v2023.11.3)

# Screen Recording

https://github.com/jitsi/jitsi-meet-electron/assets/142025785/7d3339e8-60a2-4995-8d2a-7f7fa2e9b1c6

**Comment by csett86** [comment] 2024-01-28 13:18
If the user rejects screensharing permissions, then there is only so much we can do about it. What we already do: If screensharing permission is disabled, we remove that on next launch so that the user at least gets prompted once again after relaunching the app. I would not like to bother the user more than that, thus closing this as "works as intended"

**Closed** 2024-01-28 13:18 UTC
