### ISSUE TITLE
Application Window Sharing not working

### ISSUE THREAD

**Issue by spikenheimer** [jitsi/jitsi-meet-electron#857] opened 2023-04-12 01:38 UTC
## Description

Running 2023.2.0 (installed via brew) on macos 12.6.4 (issue tested and also exists on macos 13.3.1) - Attempting to share screen but only sharing single window aka "Application window" sharing hangs the sharing screen dialog box - unable to switch back to share entire screen tab.

## Current behavior

when using the Share Screen dialog box, and attempting to switch from "Your entire screen" tab to "Application window" tab seems to freeze up the dialog until you X out or hit the "Cancel" button.   (note: entire screen does show multiple screens if multiple displays connected as expected)

Security / Privacy settings for "Screen Recording" are enabled for Jitsi Meet, as are Camera and Microphone usage etc.

## Expected Behavior

when switching to "Application window" tab expect to see all the various thumbnails of active application windows running as shown in multiple older issues regarding screen sharing.  

## Steps to reproduce

using any OS and Jitsi Meet Electron 2023.2.0 attempt to share screen, then select the "Application window" tab of that dialog

# Environment details

macOS Monterey 12.6.4
macOS Ventura 13.3.1
Xubuntu 22.04

Jitsi Meet Electron 2023.2.0 

Jitsi Meet Web 1.0.7159 (meet.jit.si on 12.04.2023)

**Comment by csett86** [comment] 2023-04-12 17:59
Just tested the same on Jitsi Meet Electron 2023.2.0 and macOS 13.3.1, together with the current jitsi-meet-web stable ([2.0.8319-1](https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_8319)), and for me its working seamlessly to switch between entire screen and application window and I can also share individual application windows as well as the full screen.

Together with the jitsi-meet-web currently deployed on meet.jit.si I can reproduce the issue, so it seems a relatively recent breakage, thank you for highlighting it. I will dig deeper

**Comment by csett86** [comment] 2023-04-12 19:26
I could also reproduce it with alpha.jitsi.net which ran jitsi-meet-web 1.0.7177 (https://github.com/jitsi/jitsi-meet/releases/tag/7177) as of now

**Comment by OrionRandD** [comment] 2023-04-12 21:57
> 

I am also getting this application-window not-sharing issue, as posted here...
https://github.com/jitsi/jitsi-meet-electron/issues/856
It seems to be a bug... I will wait then...

**Comment by saghul** [comment] 2023-04-13 06:49
If you can repro on alpha please open an issue on the jitsi-meet repo since that's where it will need to be fixed.

**Comment by OrionRandD** [comment] 2023-04-13 13:24
> If you can repro on alpha please open an issue on the jitsi-meet repo since that's where it will need to be fixed.

I think the problem is in jitsi-meet-electron itself, because if I access jitsi-meet with the webbrowser alone, I can share either the whole desktop or application window open programs or other browsers tabs...

**Comment by saghul** [comment] 2023-04-13 14:34
Not it isn't. The web version uses the browser's builtin capabilities, but the Electron version needs some parts implemented in jitsi-meet and lib-jitsi-meet to work properly.

**Comment by csett86** [comment] 2023-04-13 20:12
I have now created a fix for this as a PR: https://github.com/jitsi/jitsi-meet/pull/13208

@saghul, can you please take a look over there?

**Closed** 2023-04-14 04:12 UTC

**Comment by csett86** [comment] 2023-04-16 13:17
For reference, this is fixed in jitsi-meet-web 1.0.7184

This is already deployed on alpha.jitsi.net and beta.meet.jit.si

I will post an update here once its also live on meet.jit.si

**Comment by csett86** [comment] 2023-04-22 16:50
jitsi-meet-web 1.0.7207 is now deployed on meet.jit.si, so the fix is now live on meet.jit.si as well and application window sharing working there fine together with the electron app.

**Comment by OrionRandD** [comment] 2023-04-23 13:02
> jitsi-meet-web 1.0.7207 is now deployed on meet.jit.si, so the fix is now live on meet.jit.si as well and application window sharing working there fine together with the electron app.

Thx. A lot! Wonderful.
