### ISSUE TITLE
No icon in Ubuntu dock

### ISSUE THREAD

**Issue by probonopd** [jitsi/jitsi-meet-electron#95] opened 2018-07-21 10:34 UTC
No icon in Ubuntu 14.04 dock (and possibly others):

![icon](https://user-images.githubusercontent.com/2480569/43034738-9b3c995a-8cd1-11e8-9e18-f0ee3d5ebfd0.png)

Probably an icon needs to be set on the `BrowserWindow`?

```
win = new BrowserWindow({
   ...
   icon: path.join(__dirname, '/icon/Icon-512x512.png')
})
```

Reference:
* https://github.com/electron-userland/electron-builder/issues/2269#issuecomment-342168989

**Comment by akshitkrnagpal** [comment] 2018-07-21 10:39
@probonopd 
Thanks for this report but we are already doing that.

This is possibly a problem with Unity Desktop. I myself experience it during development and it seemed random.

Also, I read somewhere that icon does not show up when we run AppImage using terminal but works if we run the application from desktop entry.

**Comment by probonopd** [comment] 2018-07-21 10:44
> Also, I read somewhere that icon does not show up when we run AppImage using terminal but works if we run the application from desktop entry. Please try that too.

That is true only if the application does _not_ set the window icon...

**Comment by akshitkrnagpal** [comment] 2018-07-21 11:10
> That is true only if the application does not set the window icon...

I guess you are right. But we already have an icon set on the window. 
https://github.com/jitsi/jitsi-meet-electron/blob/cfd2e5382671d11dde2df667a914ca73056834e7/main.js#L177

We have tested on Ubuntu with Gnome and Fedora, so this must be problem with Unity Desktop.
I'll take a look if this is a mistake on our application side again.
Thanks for reporting this.

**Comment by probonopd** [comment] 2018-07-21 11:21
I will also try out different desktops and report back here. Thanks.

**Comment by probonopd** [comment] 2018-07-21 11:47
I can confirm that it works on Xubuntu 18.04 regardless of how it was launched:

![](https://user-images.githubusercontent.com/2480569/43035243-d784ab1e-8cdb-11e8-919f-53e6d1cbe00c.png)

**Comment by akshitkrnagpal** [comment] 2018-07-27 15:43
Hey @probonopd 

>I can confirm that it works on Xubuntu 18.04 regardless of how it was launched:

Thanks for checking that.

I also tested this on Ubuntu 18.04 and 16.04 with Unity . I couldn't find anything and I actually was unable to reproduce this on Ubuntu 16.04 with unity (on which I experienced this earlier). So I don't think this is an issue on the application side. 

Do you think we can close this? or it needs further investigation.

**Comment by probonopd** [comment] 2018-07-27 15:45
Possibly related to https://github.com/electron-userland/electron-builder/issues/748#issuecomment-408077925?

**Comment by akshitkrnagpal** [comment] 2018-07-27 15:53
Thanks  @probonopd :smile: 
I'll update electron-builder.

**Closed** 2018-07-28 11:22 UTC
