### ISSUE TITLE
Is it possible to apply uBlock Origin "prevent WebRTC from leaking your local IP" in this application?

### ISSUE THREAD

**Issue by Nokia808** [jitsi/jitsi-meet-electron#324] opened 2020-05-04 19:27 UTC
Hi dear. 

I'm a Firefox user & already disabled WebRTC to prevent leakage my ISP-provided IP while using VPN. I disabled it from "about:config" page of Firefox. This certainly prevent me from using Jitsi from my Firefox. 

Today I discovered that "uBlock Origin" add-on has a setting "prevent WebRTC from leak local IP" that If I checked, then it can prevent WebRTC from leaking my ISP-provided IP while I'm using VPN even if WebRTC enabled !

So, I did the following:
1) I re-enabled WebRTC from "about:config" page of my Firefox,
2) I restart Firefox,
3) I checked "prevent WebRTC from leaking local IP" option under "privacy" within "performance" of uBlock Origin add-on
4) I exit Firefox,
5) I  run my VPN,
6) I launched my Firefox & do conference test using https://meet.jit.si & it working okay, then checked whether WebRTC leaking my ISP-provided IP & it was (& it is) NOT !

As a sum of result, now I can use Jitsi Meet from my Firefox browser OVER VPN WITHOUT LEAKING MY ISP-PROVIDED IP, but I can not do this if I use "jitsi-meet-electron" !!

So, my suggestion is to implement this feature in your "jitsi-meet-electron" package .... Is this possible ?

**Comment by Nokia808** [comment] 2020-05-15 19:05
Hi. I would like to bring your attention to the fact that electron version 9+ will give basic support to installation add-ons - see this thread, kindly:
https://github.com/getferdi/ferdi/issues/113

Please do not misunderstand me ! I do not asking to allow users to install add-ons. All what I would like to say is that the new feature "allow to install add-ons" of electron version 9+ will make it easier for developers team of Jitsi-meet-electron to implement this feature.

Best.

**Comment by saghul** [comment] 2020-05-16 06:43
Patches are welcome, but I don’t see us spending time on this.

Note that the only entity you’d be leaking your IP to is the Jitsi Meet server you are trying to use, not generic websites trying to harvest your data.

**Comment by Nokia808** [comment] 2020-05-20 13:46
@saghul 
Dear please give attention for this VERY CRITICAL issue ! 
Please notice that the problem is NEVER with trust of honest & peoples like you ! No at all ! Moreover, you are Switzerland team !
The problem is that many of users of Jitsi are residents in outside Europe when Internet are frequently monitored & blocked by BIG BROTHERS & they enforced to use tools like VPN to overcome this. Leaking real IP by any way can make it possible for BIG BROTHERS to block VPN work....

Moreover, you add the following very very needed feature:
https://github.com/jitsi/jitsi-meet-electron/pull/343
So, why not include the feature that I suggested here in this issue ? This will help so many peoples to use your program more safely (more safely from being GRABBED BY BIG BROTHERS).

**Comment by saghul** [comment] 2020-05-20 13:56
> Dear please give attention for this VERY CRITICAL issue !

I suggest you start by dropping the hyperbole. This NOT a critical issue by any imaginable means. If you absolutely need that protection use Jitsi Meet from a browser.

> Moreover, you are Switzerland team !

Irrelevant, and wrong. We are pretty global. I myself am based in Amsterdam.

> So, why not include the feature that I suggested here in this issue ?

Because we have no time to work ALL problems. We need to prioritise. That doesn't mean it will never happen, it means you sshouldn't hold your breath.

If this is something you want to work on, I'll happily review.

**Comment by Nokia808** [comment] 2020-05-20 15:25
@saghul 
Dear forgive me if I gave statements seem to you as being hyperbole .....

You said "We need to prioritise. That doesn't mean it will never happen"
I'm respecting your priorities, & just your statement "That doesn't mean it will never happen" is enough ....

Last thing: I will send you private email to "contact@jitsi.org" since I do not know your email, to explain why this issue is important & I will ask them - if they can - forward this email to your personal email to read it & understand why I considered it critical .... I can not give more here ....

Accept my sorry again.

**Comment by Echolon** [comment] 2020-05-25 22:06
> > Dear please give attention for this VERY CRITICAL issue !
> 
> I suggest you start by dropping the hyperbole. This NOT a critical issue by any imaginable means. If you absolutely need that protection use Jitsi Meet from a browser.
> 
> > Moreover, you are Switzerland team !
> 
> Irrelevant, and wrong. We are pretty global. I myself am based in Amsterdam.
> 
> > So, why not include the feature that I suggested here in this issue ?
> 
> Because we have no time to work ALL problems. We need to prioritise. That doesn't mean it will never happen, it means you sshouldn't hold your breath.
> 
> If this is something you want to work on, I'll happily review.

Regarding Saúls comment I will close this.

If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Closed by Echolon** 2020-05-25 22:06 UTC

**Comment by Nokia808** [comment] 2020-05-27 15:29
@saghul 
@Echolon 
Hi dear. This issue seem to be fixed in chromium & chrome browser ! See the comments on the following site:
https://browserleaks.com/webrtc

```

> comment by koxopi9069 (7 months ago):
> in cromium browsers now WebRTC Leak Local IP address hide:
> Anonymize local IPs exposed by WebRTC.
> Conceal local IP addresses with mDNS hostnames. – Mac, Windows
> #enable-webrtc-hide-local-ips-with-mdns

```
