### ISSUE TITLE
Linux: 2.0.0 fails to start

### ISSUE THREAD

**Issue by monga** [jitsi/jitsi-meet-electron#231] opened 2020-04-07 14:58 UTC
[193209:0407/164939.241277:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_jitsi-KCGvvK/chrome-sandbox is owned by root and has mode 4755.

I was a happy user of the previous version, but now it fails with the above error.
I'm on an Debian unstable system (x86_64),  with kernel 5.5.1

As a workaround, I found out (see https://github.com/electron/electron/issues/17972)  that 

```sh
sudo sysctl kernel.unprivileged_userns_clone=1
```
makes it work again.

**Comment by saghul** [comment] 2020-04-07 15:03
Thanks for the report!

**Comment by btlogy** [comment] 2020-04-07 15:41
I've seen the bug while building from master yesterday.
But I was too busy getting v1.1.1 running on many devices to start digging...
Thanks to the auto-update feature, all those devices are now failing on this FATAL error after updating in the background :-/

```
FATAL:setuid_sandbox_host.cc(157)]` The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_jitsi-tMA386/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap
```

I'm using mostly Debian 10 stable with kernel 4.19.98-1.

Thanks @monga for the workaround. :+1: 
It helps me too.

And thanks everyone else to be working on improving this app. :+1: 
Got most of my family using it since the lock down.
And the electron app is much easier and perform better than the web version.

REM: I'm getting something working on Raspbian too, but with many issues to fix (unstable cam, weird noisy sound and abi error while packaging).

**Comment by gerroon** [comment] 2020-04-07 15:44
The thing about the work around is that you are going against the Debian's security settings.  And one still needs the admin rights to get that fix.

I do hope that there is a fix with this during appimage packaging.

**Comment by saghul** [comment] 2020-04-08 07:11
I could reproduce it with Ubuntu 19.10 by setting `sudo sysctl kernel.unprivileged_userns_clone=0` myself, since it seems to default to 1.

Hopefully we can solve this quickly, but if anyone has ideas on how to fix it, they'd be more than welcome.

**Comment by saghul** [comment] 2020-04-08 09:48
Tried to fix it on https://github.com/jitsi/jitsi-meet-electron/pull/235 and made a beta 4, but alas the problem persists :-/

**Comment by awlx** [comment] 2020-04-08 11:35
@saghul we also saw the Problem, that's why we released the deb so People can start the stuff with --no-sandbox, which helps those people. The problem seems only to exist for Debian Buster and running everywhere without sandbox does not seem a good idea.

**Comment by gerroon** [comment] 2020-04-08 15:29
I use other Electron apps like Trilium and Rocket.Chat, they release .deb so this is no issue

**Comment by jmcclelland** [comment] 2020-04-08 19:38
> @saghul we also saw the Problem, that's why we released the deb so People can start the stuff with --no-sandbox, which helps those people. The problem seems only to exist for Debian Buster and running everywhere without sandbox does not seem a good idea.

Where can i find the .deb file for the 2.0.0. release?

**Comment by awlx** [comment] 2020-04-09 08:09
@saghul I can make a PR to add it if interested

We build it already and it seems to work fine:
https://github.com/freifunkMUC/jitsi-meet-electron/releases/latest

**Comment by hex-m** [comment] 2020-04-13 20:01
Other Electron applications have the same problem. Riot chose to [set the SUID bit](https://github.com/vector-im/riot-web/commit/56674ea70849b3a793fa7b862945163aa10b36b8), Signal [added `--no-sandbox`](https://github.com/signalapp/Signal-Desktop/commit/1ca0d821078286d5953cf0d598e6b97710f816ef) to their launcher.

**Comment by vladimiry** [comment] 2020-04-13 21:34
SUID bit solution is not suitable for AppImage and Snap packages, so normally `--no-sandbox` gets used there (the `--no-sandbox` gets injected into the package, so end users don't need to do anything). Other package types can use the SUID bit scenario.

**Comment by saghul** [comment] 2020-04-14 07:27
@awlx Nice! Sure thing! What approach did you follow to get it working?

**Comment by awlx** [comment] 2020-04-14 07:43
It's to be honest pretty simple as electron-builder has a built target which is called "deb" :).

**Comment by vladimiry** [comment] 2020-04-14 07:48
@awlx electron-builded [sets the SUID bit for the deb package](https://github.com/electron-userland/electron-builder/commit/7c2881e52930082136f6e4b7950c3611e0e07100) but this project ships AppImage linux package only and electron-builde doesn't embed the `--no-sandbox` arg into the package yet. So right now in the case of AppImage case I simply [unpack it, apply the needed change and pack it back](https://github.com/vladimiry/ElectronMail/blob/aa4b73188b2323e317b426dad0400f075161d22d/scripts/electron-builder/build-appimage.ts).

**Comment by saghul** [comment] 2020-04-14 07:54
@awlx We don't do debs, this problem seems to manifest differently for AppImages.

@vladimiry Thanks for the insight! I think I'd go with the patching, since it's a tad simpler to maintain, at least for now.

I'll try go get a PR up later today. Thanks for the help!

**Comment by saghul** [comment] 2020-04-14 14:34
I think I misread @vladimiry 's comment 🤦  I've spent some time trying to get it to work but AFAICT doing the repackage-package dance might be the only way forward, and I have no energy left for that.

At least with the current way it will work for thoe who want to create Debian packages...

**Comment by jcz1** [comment] 2020-04-14 15:55
I vote for debian packages :-)

**Comment by tanty** [comment] 2020-04-15 10:48
Would creating a flatpak help here?

**Comment by gregorydk** [comment] 2020-04-21 16:42
> Would creating a flatpak help here?

Yes, flatpak always helps. Flatpak is so much better, flatpak runs on all distro's, has integration for all desktops and the package can be upgraded with software center if published on Flathub.

**Comment by hferreiro** [comment] 2020-08-18 10:50
> Would creating a flatpak help here?

@tanty: https://github.com/flathub/org.jitsi.jitsi-meet

**Comment by tanty** [comment] 2020-08-18 12:31
@hferreiro thanks!

https://flathub.org/apps/details/org.jitsi.jitsi-meet

**Comment by gregorydk** [comment] 2020-08-18 15:28
@hferreiro Thanks!

**Comment by saghul** [comment] 2020-10-02 07:03
CLosing as this is now documented in our readme and nothing we can act upon.

**Closed by saghul** 2020-10-02 07:03 UTC
Labels: GNU/Linux
