### ISSUE TITLE
Screen share doesn't work and permission popup has endless loop after latest update to version 2021.12.1 [Fedora KDE Wayland]

### ISSUE THREAD

**Issue by pizzadude** [jitsi/jitsi-meet-electron#677] opened 2021-12-01 23:22 UTC
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
After latest update to version 2021.12.1, on Fedora 35 KDE wayland session, when trying to screen share, I can't, and the screen share permission popup keeps duplicating in an endless loop.

## Current behavior
---
Can't enable screen sharing in KDE Wayland, and it keeps asking me over and over again for permission.

## Expected Behavior
---
Screen share to work just like last version.

## Possible Solution

---

## Steps to reproduce
---
Be on KDE 5.23.3 wayland session
Try to screen share in latest version
It won't work and you get an endless loop of permission popups

# Environment details
---
Operating System: Fedora Linux 35
KDE Plasma Version: 5.23.3
KDE Frameworks Version: 5.88.0
Qt Version: 5.15.2
Kernel Version: 5.15.4-201.fc35.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-7300U CPU @ 2.60GHz
Memory: 7.6 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 620

![image](https://user-images.githubusercontent.com/1454420/144330021-f16d99b1-96d0-43ed-85d9-dc6c557c4be5.png)

**Comment by pizzadude** [comment] 2021-12-01 23:33
It happens in both the AppImage and the unofficial flatpak, for now I guess I'll downgrade the unofficial flatpak to a previous version, since the AppImage has auto update.

**Comment by pizzadude** [comment] 2021-12-01 23:54
In CLI it shows:
[28737:1201/185245.913225:ERROR:base_capturer_pipewire.cc(990)] Failed to start the screen cast session.
[28737:1201/185246.080211:ERROR:base_capturer_pipewire.cc(990)] Failed to start the screen cast session.
[28737:1201/185246.278749:ERROR:base_capturer_pipewire.cc(990)] Failed to start the screen cast session.
[28737:1201/185246.464103:ERROR:base_capturer_pipewire.cc(990)] Failed to start the screen cast session.
[28737:1201/185246.664164:ERROR:base_capturer_pipewire.cc(990)] Failed to start the screen cast session.

**Comment by saghul** [comment] 2021-12-02 06:49
Uh so it looks like a pipe wire + electron bug :-/

**Comment by q-b** [comment] 2021-12-03 09:43
Here the whole appimage crash when clicking the sharescreen button (ubuntu mate 20.04, so no wayland, KDE or pipewire involved). Do you want me to open a new issue or can I post it here since it is related to the last upgrade ?

The output:
```
10:35:11.011 › Checking for update
[10467:1203/103511.200722:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[10415:1203/103513.031776:ERROR:nss_util.cc(286)] After loading Root Certs, loaded==false: NSS error code: -8018
10:35:13.928 › Update for version 2021.12.1 is not available (latest version: 2021.12.1, downgrade is disallowed).
10:35:13.931 › checkForUpdatesAndNotify called, downloadPromise is null
2021-12-03T09:35:17.120Z [AOT] <logInfo>:  [MAIN] handling aot-conference-joined state update from renderer process
2021-12-03T09:35:17.121Z [AOT] <logInfo>:  [MAIN] adding main window event handlers
/tmp/.mount_jitsi-5KG9Vd/jitsi-meet: line 2: 10415 Segmentation fault      (core dumped) "${BASH_SOURCE%/*}"/jitsi-meet.bin --no-sandbox "$@"

[1]  + exit 139   ~/Downloads/jitsi-meet-x86_64.AppImage
```

**Comment by saghul** [comment] 2021-12-03 09:55
Let's keep it here since it's related to screen-sharing + the latest release.

**Comment by csett86** [comment] 2021-12-03 10:44
That crash could be what is mentioned in the latest patch release 16.0.4: https://github.com/electron/electron/releases/tag/v16.0.4

especially as I could screenshare under linux (xorg, xubuntu 20.04, appimage) at least once when testing the release

**Comment by csett86** [comment] 2021-12-03 21:15
Release a fix for the crash in https://github.com/jitsi/jitsi-meet-electron/releases/tag/v2021.12.2

**Comment by vchernin** [comment] 2021-12-03 22:34
@pizzadude does latest Chromium work for you still?

**Comment by pizzadude** [comment] 2021-12-05 03:58
@vchernin Yes.

**Comment by vchernin** [comment] 2021-12-05 07:36
Ok, it sounds like an Electron specific regression then. If you can reproduce it with other apps maybe report it to https://github.com/electron/electron/issues.

**Comment by csett86** [comment] 2021-12-05 08:58
Also @pizzadude, the long-term solution for this is something along the lines of https://github.com/electron/electron/issues/30652, that @vchernin already proposed (thanks!). This whole double in-app screenshare selection and pipewire with its own selection is not a great experience anyway.

**Comment by vchernin** [comment] 2021-12-05 09:07
> This whole double in-app screenshare selection and pipewire with its own selection is not a great experience anyway.

Yeah, it seems reasonable to move away from the in app-selection with Wayland by default.

I tried puzzling out how Electron should be changed in the linked Element issue there, but I still haven't spent the time to understand how everything works...

**Comment by csett86** [comment] 2021-12-05 09:42
FYI, when trying often enough it can also work under wayland (Fedora 35, GNOME) at least if app is not running as wayland native, but xwayland + pipewire. You just need to ignore the pipewire prompts, share the full screen, and then allow all the prompts:

![wayland-screenshare](https://user-images.githubusercontent.com/1392875/144741405-de730484-3b37-4ce0-8fb5-06f2ae6fca6b.png)

Sometimes it still crashes, sometimes it works.

**Comment by vchernin** [comment] 2021-12-05 09:54
> Sometimes it still crashes, sometimes it works.

Well that's better than 0% of the time :)

Is there an electron screen sharing demo app somewhere to confirm electron broke it? I don't know of any others on 16 yet.

**Comment by vchernin** [comment] 2021-12-05 22:42
I found [this demo](https://github.com/hokein/electron-sample-apps/tree/master/desktop-capture), and I seem to be able to reproduce a similar issue (probably same root cause).

With the latest Electron 16 installed (as in the readme) sometimes I get one dialog which is correct. But sometimes I get two dialogs, which makes it difficult to actually share.

Electron 13 seems to work fine, I seem only to ever get one dialog. Electron 15 seems to behave the same as 13.

So this is probably an Electron bug, I'll report it later.

**Comment by q-b** [comment] 2021-12-06 09:16
Release [2021.12.2](https://github.com/jitsi/jitsi-meet-electron/releases/tag/v2021.12.2) fixed my problem :+1:

**Comment by vchernin** [comment] 2021-12-06 21:20
I reported the screencasting bug upstream: https://github.com/electron/electron/issues/32117

**Comment by AchMol** [comment] 2021-12-10 13:14
Hi all,
sorry, but we still have that problem with 2021.12.2 under OSX 12.0.1. and Windows 10
Two people can share a screen without problems, but with three ore more there's nothing or a blank screen. If the person who shares the screen uses native Firefox (95) all is working fine, also with more than two.

**Comment by saghul** [comment] 2021-12-10 13:20
Can you reproduce that out of the app, with Chromium?

**Comment by sweah** [comment] 2022-01-14 11:11
I still see the endless loop using version 2022.1.1 under Ubuntu 21.10. Cannot reproduce it out of the app with Chrome.

**Comment by saghul** [comment] 2022-01-14 11:27
As mentioned earlier it's a bug in Electron: https://github.com/electron/electron/issues/32117

**Comment by sweah** [comment] 2022-01-14 11:49
Oh, sorry! I thought it should have been fixed with a new electron version in a december release auf Jitsi-meet-electron

**Comment by saghul** [comment] 2022-01-14 11:51
No worries! Alas, no :-(

**Comment by vchernin** [comment] 2022-01-21 19:56
This particular bug is very Linux only, the dialogs being created rely on xdg-desktop-portal/pipewire, which don't meaningfully exist outside of Linux today. They are called by WebRTC only on Linux.

The symptons described don't really match what is doing on here, other than "not working". Could you provide more details on what exactly goes wrong?

**Comment by seanm** [comment] 2022-01-21 21:52
Yes, though I suppose I should provide them in a new ticket. Not sure which project to file it under though.

Screen sharing works better from Firefox and worse with the electron app (part of why I thought this was the bug I'm experiencing) but even in Firefox it doesn't work great. And it happens with Windows or Mac.

I suppose the issue is more likely to be server-side come to think of it, since it happens with so many clients on so many OSes.

**Comment by ljrk0** [comment] 2022-02-03 11:30
> FYI, when trying often enough it can also work under wayland (Fedora 35, GNOME) at least if app is not running as wayland native, but xwayland + pipewire. 

For me it works flawlessly with native wayland, although it's missing window decorations of course.  However, electron17 just landed CSDs: https://github.com/electron/electron/pull/32650. So hopefully this jitsi can update soon (or use the maybe-to-come electron16.x backport).

**Comment by pizzadude** [comment] 2022-02-19 14:33
Seems to be fixed for me. Fedora 35 KDE Wayland. KDE 5.24.1, latest Jitsi Meet flatpak

Can anyone else confirm?

Full system info:
```
Operating System: Fedora Linux 35
KDE Plasma Version: 5.24.1
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.2
Kernel Version: 5.16.9-200.fc35.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-7300U CPU @ 2.60GHz
Memory: 7.6 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 620
```

**Comment by ljrk0** [comment] 2022-02-19 14:41
Yes, the Flatpak got updated
https://github.com/flathub/org.jitsi.jitsi-meet/pull/42
to 2022.2.1 which itself upgraded to Electron 17
https://github.com/jitsi/jitsi-meet-electron/pull/711 which contains the fix I mentioned in the previous comment.

**Comment by saghul** [comment] 2022-02-19 15:09
Thanks for confirming folks!

**Closed by saghul** 2022-02-19 15:09 UTC

**Comment by chefexperte** [comment] 2025-02-27 11:04
I am currently having the same issue on newest Fedora with Gnome and Wayland using the Jitsi Meet Flatpak :/
