### ISSUE TITLE
How to change UI of this app and can I use this code with my own NodejS-socket video bridge server ?

### ISSUE THREAD

**Issue by simformsolutions** [jitsi/jitsi-meet-electron#239] opened 2020-04-08 11:01 UTC
I am not sure how this electron app gets its UI from where but  I want to understand that If I create my own nodejs xmpp server and use electron code with that then what changes I need to make to work with it?

Is this UI of Electron comes from any server as iFrame ?

@saghul  Please guide!

**Comment by Echolon** [comment] 2020-06-02 20:29
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org first.

I will close this issue till then.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Closed by Echolon** 2020-06-02 20:29 UTC
Labels: question
