### ISSUE TITLE
electron-installer with command-line parameter to change default server url

### ISSUE THREAD

**Issue by mschwehl** [jitsi/jitsi-meet-electron#751] opened 2022-04-28 12:57 UTC
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
electron-installer with command-line parameter to change default server url
When an organisation does make a rollout from the jitsi-client there is the need to pre-configure it for the enduser

## Current behavior
no command-line parameter for default url

## Expected Behavior
calling the installer with parameter
jitsi-meet-electron.exe -defaultURL=https://meet.some.org -installDir=c:\somedir

## Possible Solution
add parameter to configure setup

## Steps to reproduce

# Environment details
Windows

**Comment by csett86** [comment] 2022-07-03 18:48
Closing as a duplicate of #337

**Closed by csett86** 2022-07-03 18:48 UTC
