### ISSUE TITLE
[Feature request] Allow user to delete a room from heir/his UI

### ISSUE THREAD

**Issue by Nokia808** [jitsi/jitsi-meet-electron#322] opened 2020-05-02 06:31 UTC
Hi dears.

After trying this nice package, I found an issue need to be covered:
Suppose that a user created a conference room. Then after, she/he found that it's name not appropriate or not long enough, so she/he will create new room with suitable name. Now, user not like to use previous room any more ... But the old room that user has no need to use it more will stick in the UI of application & can not removed currently ... 

I suggest on you to add new option that allow user to delete already created/joined room(s) from application UI.

Please notice that my request is allow user to delete already created/joined foom(s) from application UI not from server ... I'm not talking about server, but I'm talking about local deletion from UI ...

I think this new feature should be available on your official web application & all other platform specific applications ....

**Comment by svoop** [comment] 2020-05-14 09:39
Second that, it's really cumbersome and error prone to dive into the JSON file and remove the right parts by hand to get rid of a room on the UI.

**Comment by Nokia808** [comment] 2020-05-14 10:12
Currently I'm enforced to manually delete

home/myusername/.config/Jitsi Meet

folder so as to delete an unused room URL but this will delete all program catch ! This is bothering ...

**Comment by saghul** [comment] 2020-05-14 12:34
A PR would be welcome.

**Comment by svoop** [comment] 2020-05-14 12:37
@saghul It will be a while before I can look into that, got a shoutload of work for other FOSS projects on my desk already. So maybe someone else wants to chime in? Shouldn't be too difficult.

**Comment by Echolon** [comment] 2020-05-25 22:12
I think this is a duplicate of #127 and #283

**Closed** 2020-05-25 22:13 UTC
Labels: enhancement
