### ISSUE TITLE
Wayland native no screenshare without explicit WebRTCPipeWireCapturer enabled

### ISSUE THREAD

**Issue by 9Lukas5** [jitsi/jitsi-meet-electron#682] opened 2021-12-04 13:23 UTC
## Description

Running Jitsi on Wayland without additional parameters (running in XWayland mode) the Screenshare through Pipewire is working out of the box.
If Jitsi get's started in wayland native mode, the screenshare with Pipewire isn't working anymore, unless the WebRTCPipeWireCapturer feature is enabled explicitly, too.

---

## Current behavior

Running Jitsi in Wayland native mode needs explicit enablement of the WebRTCPipeWireCapturer feature for working screenshare

---

## Expected Behavior

No additional explicit flag needed for wayland native execution to use Pipewire for screenshare

---

## Possible Solution
---

## Steps to reproduce

Run Jitsi with ozone platform `wayland` but don't explicitly enable the ozone feature `WebRTCPipeWireCapturer`

```
<path to bin> --enable-features=UseOzonePlatform --ozone-platform=wayland
```

---

# Environment details

Ubuntu 20.04 Focal Fossa
Gnome 41 on Wayland
Jitsi 2021.11.2
Pipewire 0.3.40

---

**Comment by saghul** [comment] 2021-12-04 19:11
IIRC that feature is experimental still, that's why it's not enabled by default.

**Comment by 9Lukas5** [comment] 2021-12-04 21:26
But if I'm running Jitsi without additional parameters it is using the Pipewire capturing obviously, as the screenshare works and the authorization popup from the system comes up.

But if I now set the parameters that Jitsi itself is running as a wayland native application, it doesn't use Pipewire anymore unless I set the WebRTCPipeWireCapturer feature as well.  
So, yes the wayland native execution is experimental and that's what I'm setting on purpose. But the usage of Pipewire for the screenshare seems to be enabled by default already, but somehow disabled/broken when running Jitsi in Wayland-native.

**Comment by csett86** [comment] 2021-12-04 21:32
Yes, because we pass the WebRTCPipeWireCapturer feature by default, but only if you do not manually specify any "enable-features" flags: https://github.com/jitsi/jitsi-meet-electron/blob/master/main.js#L44-L46

Feel free to submit a PR, but keep im mind this all a experimental stage and has some refinements, eg https://github.com/jitsi/jitsi-meet-electron/pull/630

**Comment by csett86** [comment] 2021-12-05 08:54
As written by @vchernin in https://github.com/jitsi/jitsi-meet-electron/issues/681#issuecomment-986162338, 

> Note you shouldn't need --enable-features=UseOzonePlatform regardless since that should be on by default now (at least in recent Chromium).

I can reproduce that, if you just launch jitsi meet electron with

    <path to bin> --ozone-platform=wayland

screensharing pipewire popups again come up, still broken as in #677 

Thus I'll close this one.

**Closed by csett86** 2021-12-05 08:54 UTC

**Comment by 9Lukas5** [comment] 2021-12-05 09:11
Ok, just to confirm: I guess that's the case for 2021.12.1 (electron update from 13 to 16) and newer, right?
Because in 2021.11.2 it will open in XWayland if the enable-features parameter is left out.

**Comment by csett86** [comment] 2021-12-05 09:28
Yes, thats the case for 2021.12.1 with electron 16. You are right, electron 13 probably still does not have ozone platform as default.
