### ISSUE TITLE
Advert cannot be closed

### ISSUE THREAD

**Issue by rlees85** [jitsi/jitsi-meet-electron#765] opened 2022-06-28 08:39 UTC
## Description
---
When finishing a meeting with the Jitsi electron client, the advert that appears cannot be closed. The advert should be closable or even better not exist (but I understand people have to make money).

## Current behavior
---
When finishing a meeting with the Jitsi electron client, the advert that appears cannot be closed. This blocks navigation back to the main screen.

## Expected Behavior
---
Any adverts that appear should have a clear way to be closed.

## Possible Solution
---
- Add a clear "X" to close the advert
- Do not use adverts (Jitsi in a browser seems not to)

## Steps to reproduce
---
- Start a meeting
- Stop meeting
- Huge blocking advert appears

# Environment details
---
Arch Linux using AUR package modified with latest version (2022.6.1)

**Comment by saghul** [comment] 2022-06-28 08:54
Duplicate of https://github.com/jitsi/jitsi-meet-electron/issues/763

**Closed by saghul** 2022-06-28 08:54 UTC
