### ISSUE TITLE
Debian package provide a not-working /usr/bin/jitsi-meet script

### ISSUE THREAD

**Issue by b3** [jitsi/jitsi-meet-electron#689] opened 2021-12-15 15:59 UTC
## Description

I installed the provided `jitisi-meet-amd64.deb` on my Debian 11 box using the following command :

```console
apt-get install ./jitsi-meet-amd64.deb`
```
---

## Current behavior

When I try to start `jitsi-meet` from a terminal command line I get the following error: 

```console
$ jitsi-meet 
/usr/bin/jitsi-meet: line 2: /usr/bin/jitsi-meet.bin: No such file or directory
```

---

## Expected Behavior

The app should start normally.

---

## Possible Solution

The trouble is with the `/usr/bin/jitsi-meet` bash script which try to start a file called `jitsi-meet.bin` in the same folder as itself which is not present.

The line which causes the trouble is :

```bash
"${BASH_SOURCE%/*}"/jitsi-meet.bin --no-sandbox "$@"
```

In fact this file is copied by the `jitsi-meet-electron.postinst` config script which simply creates a symbolic link : 

```bash
ln -sf '/opt/Jitsi Meet/jitsi-meet' '/usr/bin/jitsi-meet'
```

As I do not clearly understand how the `.deb` file is created (through github CI features I guess) I do not know what is the best solution.

However I imagine that solving the problem could be done by changing this line to something like :

```bash
ln -sf '/opt/Jitsi Meet/jitsi-meet.bin' '/usr/bin/jitsi-meet'
```

---

# Environment details

```console
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```
---

**Comment by csett86** [comment] 2021-12-15 16:08
Thank you for reporting it in detail!

Yes, this is known and next release will have this fixed: https://github.com/jitsi/jitsi-meet-electron/commit/f0d020adf931f477d290589417054db7f3ee4d1a

**Comment by csett86** [comment] 2021-12-15 16:09
(Duplicate of #628)

**Closed** 2021-12-15 17:01 UTC

**Comment by b3** [comment] 2021-12-15 17:33
Sorry for the duplicate.
I did not find the issue even I have looked for it, clearly not deeply enough.

**Comment by saghul** [comment] 2021-12-16 09:41
No worries!
