### ISSUE TITLE
Application translation

### ISSUE THREAD

**Issue by susobaco** [jitsi/jitsi-meet-electron#288] opened 2020-04-21 11:41 UTC
Hi, I'd like to translate the application into Spanish. Which files need translation?
Salud!

**Comment by KovalevArtem** [comment] 2020-04-22 12:04
https://github.com/jitsi/jitsi-meet/issues/5056

**Comment by KovalevArtem** [comment] 2020-04-22 12:07
#https://github.com/jitsi/jitsi-meet/issues/5056

**Comment by KovalevArtem** [comment] 2020-04-22 12:07
Duplicate of #jitsi/jitsi-meet#5056

**Comment by KovalevArtem** [comment] 2020-04-22 12:08
Duplicate of #https://github.com/jitsi/jitsi-meet/issues/5056

**Comment by susobaco** [comment] 2020-04-22 14:55
thanks

**Comment by KovalevArtem** [comment] 2020-04-22 14:58
@saghul But the application itself also has a minimal interface, which would be nice to translate!
![image](https://user-images.githubusercontent.com/36500228/79997923-c01efe80-84c2-11ea-8934-4c34bb50c55e.png)

**Comment by susobaco** [comment] 2020-04-22 15:06
I was referring to this interface, the jitsi-meet-electron

**Comment by susobaco** [comment] 2020-04-25 18:31
Sorry, but I can't find the project to translate

**Comment by ctr49** [comment] 2020-04-26 22:01
The app does not use internationalization yet, so there is no place to translate things unfortunately. See #278

**Comment by susobaco** [comment] 2020-04-27 15:50
But, you're scheduled to have it, right? I'm leaving the issue open and waiting.

**Comment by freddytuxworth** [comment] 2020-06-26 14:44
@susobaco Internationalisation is now added so you could make a PR to add Spanish. See [this PR](https://github.com/jitsi/jitsi-meet-electron/pull/399/files) for an example/template.

**Closed** 2021-03-04 09:13 UTC
Labels: localization
