### ISSUE TITLE
a JavaScript error occured in the main process

### ISSUE THREAD

**Issue by dchmelik** [jitsi/jitsi-meet-electron#755] opened 2022-05-14 10:20 UTC
## Description

'A JavaScript error occured in the main process usually pops up over & over.
![Screenshot_2022-05-14_03-09-51](https://user-images.githubusercontent.com/10347890/168426974-35519521-8f78-488c-a5be-77930610fb84.jpg)

## Current behavior
'A JavaScript error occured in the main process' usually pops up over & over.

## Expected Behavior
Don't have JavaScript error in main process.

## Steps to reproduce
Start jitsi-meet.

# Environment details
Slackware64 GNU/Linux 15, 15.1-current, up-to-date

**Comment by csett86** [comment] 2022-05-14 11:24
@dchmelik please upload the screenshot directly here and post the version number of the Jitsi Meet Electron App you are trying to use

**Comment by dchmelik** [comment] 2022-05-14 12:25
Seems no way to upload here.  It started with the version last November and continued through the version this April.

**Comment by saghul** [comment] 2022-05-14 13:01
You can just drag the screenshot into the text area.

**Comment by dchmelik** [comment] 2022-05-14 13:06
Done (above.)

**Comment by saghul** [comment] 2022-05-14 13:45
You are using the AppImage, right?

**Comment by dchmelik** [comment] 2022-05-14 13:46
yes

**Comment by csett86** [comment] 2022-05-14 14:05
@dchmelik, can you quickly check whether November version (https://github.com/jitsi/jitsi-meet-electron/releases/tag/v2021.11.1) still works or if thats also already non-functioning for you. I would like to understand whether its due to the updates required / triggered by the electron 16 upgrade or already before that.

**Comment by dchmelik** [comment] 2022-05-15 01:10
I rechecked and after several minutes 2021-11-1 was doing okay, but sometimes you have to wait several hours or overnight a couple days for the bug to start.  Sometimes it starts immediately.  I'm 100% sure it was happenning by 2021-11-2 and every subsequent, which I mentioned on IRC last November but was ignored.

**Comment by saghul** [comment] 2022-05-15 03:59
FTR there is no oficial IRC channel we use. Our community forum and issue trackers are the ways we use to communicate with users.

**Comment by csett86** [comment] 2022-07-03 18:48
So this seems to be a Slackware and electron specific issue, @dchmelik, can you please check if it still occurs with the latest version v2022.6.1, because that contains the latest and greatest electron 19.

**Comment by csett86** [comment] 2022-07-11 20:03
As no comment from original requester, closing this as unable to reproduce

**Closed by csett86** 2022-07-11 20:03 UTC

**Comment by dchmelik** [comment] 2024-04-16 07:13
I think same is happening on Ubuntu/Mint/Neon (22.04) and that it's not just a Slackware issue... but I have to double-check the error message that keeps popping up.
