### ISSUE TITLE
Use electron with Pipewire to support screensharing under Wayland

### ISSUE THREAD

**Issue by snaggen** [jitsi/jitsi-meet-electron#567] opened 2021-04-28 17:37 UTC
## Description
After Electron 8.2.2 version the rtc_use_pipewire=true build flag to support Wayland screen sharing
So by making sure the builds you provide is based on electron with this build flag, you should get proper screen sharing support under Wayland. And this is probably going to be more of an issue now, when Ubuntu released with wayland as default.

**Comment by snaggen** [comment] 2021-04-28 17:56
Ok, before electron v12 it was only in an experimental branch, but electron v12 should contain the pipewire fixes with RTC_USE_PIPEWIRE build flag according to the all mighty Internet.

**Comment by saghul** [comment] 2021-04-28 18:23
My understanding is there are 2 command line flags you can use when launching the app to get Wayland support. I'm not 100% sure this fixes screen-sharing.

We are not going to be making custom Electron builds, however. Once upstream Electron has it, we'll use it.

**Comment by snaggen** [comment] 2021-04-28 18:39
It seems that official builds of electron now should have the rtc_use_pipewire enabled by default according to https://github.com/electron/electron/issues/23063#issuecomment-744339286
In that thread it is claimed that the flag --enable-features=WebRTCPipeWireCapturer is required, so I tested this with the appimage. Which then just give me a broken image instead of a window
![bild](https://user-images.githubusercontent.com/6420639/116455738-ba8c8f00-a861-11eb-9392-04a081345644.png)

**Comment by saghul** [comment] 2021-04-28 19:08
Did you also set these? 

--enable-features=UseOzonePlatform --ozone-platform=wayland

**Comment by snaggen** [comment] 2021-04-29 06:16
No, I originally only used --enable-features=WebRTCPipeWireCapturer , since I know that in Chromium the use of Pipewire is not dependent on Wayland. I have working WebRtc in Chromium through pipewire using XWayland in Fedora 33/34. So I assume this is far more stable then the rest of the wayland related changes. 
But I tested to also add the flags you suggested --enable-features=UseOzonePlatform --ozone-platform=wayland , and that gave me a Wayland version (but since they do not support CSD yet, I got no decorations) but now the screensharing was back to X only strangely enough. In the application windows view, I see only my X applications listed. That was not what I expected.

**Comment by saghul** [comment] 2021-04-29 08:17
It's labeled as experimental AFAIK, so it may take a few more versions to get there I'm afraid.

**Comment by snaggen** [comment] 2021-04-29 08:52
I wonder if the pipewire thing is a version 0.2 vs 0.3 issue? https://jgrulich.cz/2020/12/18/webrtc-chromium-updates-in-2020/ states there are a rtc_pipewire_version in Chromium 89. And fedora 34 is using pipewire 0.3
And pipewire have been in chromium for a long time, is that really classified as experimental? Isn't that even included in Chrome?

**Comment by saghul** [comment] 2021-04-29 11:22
Sorry, I don't know the answer to those.

**Comment by vchernin** [comment] 2021-05-12 02:54
@snaggen I made a PR to [package the Slack flatpak with PipeWire 0.2.x](https://github.com/flathub/com.slack.Slack/pull/118), which works on Fedora 34 despite Fedora shipping with PipeWire 0.3.x. So 0.3.x should be backwards compatible in that sense. I don’t know what Electron version Slack ships.  

@saghul does Jitsi ship with the latest Electron v12 official build? That detail will help as I want to open an upstream bug for this. It seems apps [like Element](https://github.com/vector-im/element-web/issues/17156) also experience this issue despite being on a recent Electron version.

**Comment by csett86** [comment] 2021-05-12 04:39
Yes, Jitsi is generally up to date with Electron and release 2.8.6 ships with Electron 12.0.6.

**Comment by vchernin** [comment] 2021-05-12 06:15
[Upstream feature request to build Electron with PipeWire by default](https://github.com/electron/electron/issues/29115).

**Comment by Yajo** [comment] 2021-05-12 07:13
So, should it be fixed here or [in the flatpak](https://github.com/flathub/org.jitsi.jitsi-meet)?

**Comment by saghul** [comment] 2021-05-12 09:30
Neither. It needs to be fixed in Electron first: https://github.com/electron/electron/issues/29115

**Comment by csett86** [comment] 2021-05-12 16:25
I just retested this on Fedora 34 and the current 2.8.6 Jitsi Meet AppImage and it already works fine: Launch the AppImage with `--enable-features=WebRTCPipeWireCapturer` and the PipeWire prompt comes up and screensharing works.

Current glitch only: The preview/selection screen from Jitsi creates continuous prompts while rendering and does not properly display a preview. Just allow once in PipeWire, then continue in the Jitsi selection screen and then allow all remaining PipeWire promts.

Having it working in the flatpak just seems to be adding the enable-features flag (either here in our linux launcher script or in the flatpak desktop file. As PipeWire will become the default, I tend to add it via the script that is already adding the --no-sandbox flag: https://github.com/jitsi/jitsi-meet-electron/blob/master/linux-sandbox-fix.js#L15. But before doing that, I want to test that the flag does not have any side-effects on non-pipewire systems.

**Comment by vchernin** [comment] 2021-05-12 16:33
@csett86 that is some good news, it potentially means the upstream bug report I made can be closed. I will test out Jitsi meet more extensively to try to reproduce your success.

I am curious though can you get Element working as well? I was never able to get Element working with that flag using their deb package. It’s possible there maybe only is a build issue with Element and we don’t necessarily need an upstream fix. (I tested the deb in a vm which since I’m also on fedora).

If Jitsi is already built with Electron support it means Element might be as well, which all together means most Electron apps already have PipeWire. The only other app I know of with broken PipeWire is Teams which is proprietary and seemingly on an old version of Electron.  

See the upstream bug report I linked above for all sorts of different information.

**Comment by vchernin** [comment] 2021-05-12 17:59
@csett86 I also managed to get the pipewire pop up in the Jitsi Meet AppImage 2.8.6, it seems I am experiencing a similar issue as described, the prompts don't really work. However, I was never actually able to properly screen share. Can you confirm you could view the share on another device?

I will note I am on fedora 34 silverblue, but I don't think that should make a difference as pipewire works in other apps.
When I try to screen share I always get this error:
```
./jitsi-meet-x86_64.AppImage --enable-features=WebRTCPipeWireCapturer
[18549:0512/102048.620065:ERROR:base_capturer_pipewire.cc(522)] Failed to load the PipeWire library and symbols.
```
I will play around with the flaptak and see if I can get that working.

**Comment by csett86** [comment] 2021-05-12 18:07
That is strange, as yes, I used Fedora Workstation 34 and was able to see the shared screen on a second device (iOS with Jitsi app to be precise).

I also launched the appImage just like you described in the previous comment.

I will also try to set the flag by default either in the main.js where the other flags are set or via the wrapper script.

The only issue I had were multiple permission popups during the preview pane, but ignoring that and pressing share I could successfully share the full screen.

I will experiment a bit to see whether sharing individual windows also works as expected.

**Comment by vchernin** [comment] 2021-05-12 18:10
@csett86 See my update in that comment, the flatpak worked for me while the appimage did not. 

If the flag is set by default in main.js do you think that will apply to the flatpak as well? Still I can easily make a PR to add the flag to the flatpak as well.

**Closed** 2021-05-12 20:16 UTC

**Comment by t2d** [comment] 2021-06-22 09:34
May I ask, when the next release is planned, so we can use this feature? Currently, I'm using the ungoogled chromium flatpak to have screenharing with Jitsi. But I would much prefer to use the Jitsi flatpak instead.

**Comment by vchernin** [comment] 2021-06-22 15:37
@t2d for the time being you should be able to do:
`flatpak run org.jitsi.jitsi-meet --enable-features=WebRTCPipeWireCapturer`

**Comment by csett86** [comment] 2021-06-26 08:55
@t2d The fix is now also released as 2.8.7 (incl. to flathub: https://github.com/flathub/org.jitsi.jitsi-meet/pull/22)

**Comment by t2d** [comment] 2021-06-30 08:03
On Fedora 34 the problems seems to persist with version 2.8.7
![Screenshot from 2021-06-28 09-14-35](https://user-images.githubusercontent.com/1834580/123924497-52097d80-d98a-11eb-94e2-e434034ca692.png)
![Screenshot from 2021-06-28 09-14-27](https://user-images.githubusercontent.com/1834580/123924502-52a21400-d98a-11eb-9842-e2162ed8723d.png)

**Comment by vchernin** [comment] 2021-06-30 08:07
@t2d the preview images may not work, but once you click the share button (for you it says "Teilen") it should work.

Are you on the AppImage or Flatpak?

I'd recommend trying the Flatpak as that works out of the box for me on Fedora 34.

**Comment by snaggen** [comment] 2021-06-30 11:42
I see this on Fedora 34 using Flatpak. But as you say, if I select the broken preview it seems that sharing actually works.

**Comment by snaggen** [comment] 2021-07-02 06:17
I also still see this on Fedora 34 using both the Flatpak from Flathub and the Appimage with version 2.8.8

**Comment by vchernin** [comment] 2021-07-02 06:20
@snaggen Could you open a new bug for this broken preview image issue? It’s definitely not intended behaviour, but I think it’s best suited in a new bug as this one achieved it’s main goal (pipewire support).

**Comment by snaggen** [comment] 2021-07-02 09:59
But isnt the preview part of the pipewire support, since it would use pipewire to view the preview.

//Mattias Eriksson



2 juli 2021 08:20 av ***@***.***:

**Comment by vchernin** [comment] 2021-07-02 13:41
I suppose, @csett86 do you want to open a new issue or stay in this one?

**Comment by t2d** [comment] 2021-07-02 15:24
I opened #608 for the preview issue

**Comment by arlt** [comment] 2021-07-05 10:20
Ubuntu 21.04 here

Flatpak 2.8.8 (without additional parameters):
- Screen sharing works
- Preview is broken

AppImage 2.8.8 (without additional parameters):
- Screen sharing is broken: `ERROR:base_capturer_pipewire.cc(522)] Failed to load the PipeWire library and symbols.`
- Preview is broken

For completeness - Chromium 91.0.4472.114:
- Screen sharing (window) - first use: hangs for 25 seconds with several messages:
```
[193984:193984:0705/121147.908807:ERROR:sandbox_linux.cc(374)]
InitializeSandbox() called with multiple threads in process gpu-process.
[193984:193984:0705/121148.028375:ERROR:gl_surface_presentation_helper.cc(259)]
GetVSyncParametersIfAvailable() failed for 1 times!
[193984:193984:0705/121148.040395:ERROR:gl_surface_presentation_helper.cc(259)]
GetVSyncParametersIfAvailable() failed for 2 times!
[193984:193984:0705/121148.043441:ERROR:gl_surface_presentation_helper.cc(259)]
GetVSyncParametersIfAvailable() failed for 3 times!
[193984:193984:0705/121148.047849:ERROR:shared_image_manager.cc(214)]
SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[193984:193984:0705/121148.048606:ERROR:shared_image_manager.cc(214)]
SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[193984:193984:0705/121148.049227:ERROR:shared_image_manager.cc(214)]
SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
... (48 times)
```
- Screen sharing (window) - second use: works
- Preview: works (window)

**Comment by vchernin** [comment] 2021-07-05 18:29
I couldn't get screensharing working on the AppImage either, however, according to https://github.com/jitsi/jitsi-meet-electron/pull/584 it should work.

Perhaps it will get better when Jitsi updates to Electron 13, which defaults to using PipeWire 0.3 instead of 0.2.

**Comment by rohmishra** [comment] 2022-01-08 02:02
![Screenshot from 2022-01-07 21-01-18](https://user-images.githubusercontent.com/2221064/148627319-8f06c064-ea36-409c-8353-80a14ba9b590.png)

Jitsi just keeps spamming share menu without allowing me to select anything.

**Comment by saghul** [comment] 2022-01-08 07:01
There is nothing we can do, it's an Electron / Chrome bug.

**Comment by rohmishra** [comment] 2022-01-10 01:32
I see. I assume electron repeatedly tries to start a stream causing this? I haven't seen this happen on chrome.

**Comment by saghul** [comment] 2022-01-10 10:05
Chrome uses a different implementation: getDisplayMedia. Not sure how much code is shared between that and what Electron does.

**Comment by AwesomeDummy** [comment] 2023-06-05 06:40
> Did you also set these?
> 
> --enable-features=UseOzonePlatform --ozone-platform=wayland

How can we set these flags in our electronjs app?

**Comment by sunknudsen** [comment] 2023-07-15 13:40
Hey @AwesomeDummy!

```typescript
import { app } from "electron"

app.commandLine.appendSwitch("enable-features", "WebRTCPipeWireCapturer")
```
