### ISSUE TITLE
Jitsi meet electron in webview - screen sharing problem

### ISSUE THREAD

**Issue by khoneb** [jitsi/jitsi-meet-electron#844] opened 2023-02-09 21:41 UTC
Hi everyone.

## Description
I'm trying to implement screen sharing in an electron application. The difference is that I'm not implementing jitsi meet directly in electron. My electron just load an existing website that uses Jitsi. 

## Current behavior
Whenever I try to use the screen sharing, I get the [features/desktop-picker] Called JitsiMeetElectron.obtainDesktopStreams but it is not defined.

## Expected Behavior
I would like to be able to use screen sharing in electron through a webview.

## Possible Solution
I'm guessing that Electron needs a chrome extension to make it work

**Comment by saghul** [comment] 2023-02-10 08:15
You need to use the electron SDK sister project in order to enable that.

**Comment by khoneb** [comment] 2023-02-10 14:21
@saghul Thanks a lot ! And where could I find this SDK sister project ? Do you mean the jitsi-meet-electron-sdk ?

**Comment by saghul** [comment] 2023-02-10 15:04
Sorry, yeah that's `jitsi-meet-electron-sdk`. You can see how the different features can be enabled in the README.

**Comment by khoneb** [comment] 2023-02-10 15:07
@saghul Yes i tried this but unfortunatly it doesn't seem like it's for my use case. 
For instance in the readme.md it says that i need to enable screen sharing through 

```
// api - The Jitsi Meet iframe api object.
setupScreenSharingRender(api);
```

But in Electron I don't have access to the api object. The Jitsi Meet Iframe API object is in the webapp code that my electron is encapsulating.

**Comment by saghul** [comment] 2023-02-10 15:09
Then alas you are out of luck. The way Electron exposes the API it needs direct communication with the page doing the share.

**Comment by khoneb** [comment] 2023-02-10 15:14
That's a sad news. So you think that there is no solutions for this ? Even if I add to my electron some chrome extensions that allows the screen sharing ? When I started this 4 years ago I had the impression that it was a solution.

**Comment by saghul** [comment] 2023-02-10 15:22
That has never been the case in Electron.

The problem is the screen-sharing API does not present any UI in Electron. Thus, we need to draw our own UI. In order to coordinate with Electron there needs to be a communication channel established between the app and Electron.

**Comment by saghul** [comment] 2023-02-10 18:20
As far as I know, yes.

**Comment by saghul** [comment] 2023-05-09 11:24
Closing since there is nothing that we can do here.

**Closed by saghul** 2023-05-09 11:24 UTC
