### ISSUE TITLE
Screen sharing previews broken

### ISSUE THREAD

**Issue by ubmarco** [jitsi/jitsi-meet-electron#508] opened 2021-01-22 08:28 UTC
## Description
---

The screen share preview window shows broken images.

## Current behavior
---

![image](https://user-images.githubusercontent.com/839934/105465757-a13cdb00-5c93-11eb-99c7-e7e6d72d61e1.png)

![image](https://user-images.githubusercontent.com/839934/105465892-ce898900-5c93-11eb-8628-dd11a93e18f8.png)

## Expected Behavior
---
The screen share preview window shows the window's contents.

## Possible Solution
---

## Steps to reproduce
---
Click on the screen share button.
# Environment details
---
Manjaro Linux 20.2.1, 64bit, jitsi-meet-electron version 2.4.2

**Comment by saghul** [comment] 2021-02-23 12:12
Cannot reproduce this.

**Comment by ubmarco** [comment] 2021-02-23 12:24
Hmm ok. Maybe I can provide some logs? When looking into the debug toolbar, I see a lot of requests of the following type when opening the screen share window:
![image](https://user-images.githubusercontent.com/839934/108842890-3ce6a180-75da-11eb-83e0-e468ddd189fe.png)
Here is the response tab:
![image](https://user-images.githubusercontent.com/839934/108842928-4a9c2700-75da-11eb-8387-a6c6a4f5d149.png)
These are base64 encoded png images.

**Comment by saghul** [comment] 2021-02-23 12:31
Those are provided by Electron itself, we just render them. Any chance you are using wayland?

**Comment by ubmarco** [comment] 2021-02-23 15:08
No, I'm using X11.
```
marco@tux01 ~ loginctl
SESSION  UID USER  SEAT  TTY
      2 1002 marco seat0    

1 sessions listed.

marco@tux01 ~ loginctl show-session 2 -p Type
Type=x11
```
This is my `neofetch` output:
![image](https://user-images.githubusercontent.com/839934/108863262-4d564680-75f1-11eb-8a7e-be99ddddbe4b.png)

**Comment by saghul** [comment] 2021-02-23 21:10
That's odd. Can you try the freshly released 2.5 version?

**Comment by ubmarco** [comment] 2021-02-25 11:11
I updated to 2.5.1 using the package https://aur.archlinux.org/packages/jitsi-meet-desktop-bin/. Still the same issue.
Are there any logs I can investigate?
The screen share preview works perfectly in Chromium.

**Comment by saghul** [comment] 2021-02-25 11:33
Please use our release not AUR to test it.

**Comment by ubmarco** [comment] 2021-02-25 12:16
I downloaded https://github.com/jitsi/jitsi-meet-electron/releases/download/v2.5.1/jitsi-meet-x86_64.AppImage, made it executable and started it. I see the same issue.
This is the startup log:
```
** (AppImageLauncher:123834): WARNING **: 13:15:57.659: Pixbuf theme: Cannot load pixmap file /usr/share/themes/Arc/gtk-2.0/assets/trough-progressbar.png: Failed to load image “/usr/share/themes/Arc/gtk-2.0/assets/trough-progressbar.png”: Fatal error in PNG image file: bad parameters to zlib


(AppImageLauncher:123834): GdkPixbuf-CRITICAL **: 13:15:57.659: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:123834): GdkPixbuf-CRITICAL **: 13:15:57.659: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

** (AppImageLauncher:123834): WARNING **: 13:15:57.659: Invalid borders specified for theme pixmap:
        /usr/share/themes/Arc/gtk-2.0/assets/trough-progressbar.png,
borders don't fit within the image

(AppImageLauncher:123834): GdkPixbuf-CRITICAL **: 13:15:57.659: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

.
.
.

(AppImageLauncher:123834): GdkPixbuf-CRITICAL **: 13:15:57.659: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(AppImageLauncher:123834): GdkPixbuf-CRITICAL **: 13:15:57.659: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
13:15:58.696 › Checking for update
(node:123845) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(electron) 'BrowserWindow.getDevToolsExtensions' is deprecated and will be removed. Please use 'session.getAllExtensions' instead.
13:15:59.441 › Update for version 2.5.1 is not available (latest version: 2.5.1, downgrade is disallowed).
13:15:59.442 › checkForUpdatesAndNotify called, downloadPromise is null

```

**Comment by saghul** [comment] 2021-02-25 13:20
I have no idea why it fails :-(

**Comment by ubmarco** [comment] 2021-02-25 20:14
I tested a little more and it has something to do with the Jitsi Meet server from mailbox.org I use!
I created a temporary room so you can see the issue: https://businessvideo.mailbox.org/TempTestForGithubIssue508.
PW is `6cS3vM0h`. However when I join mailbox.org meetings with Chromium I see the previews.

I tried some other Jitsi servers and the screen share previews are shown with the native app.
Do you see the issue on jitsi-meet-electron side or on mailbox.org?

**Comment by ubmarco** [comment] 2021-02-25 20:21
I also asked for help on the mailbox.org user forum:
https://userforum.mailbox.org/topic/5590-jitsi-meet-electron-screen-share-previews-broken

**Comment by saghul** [comment] 2021-02-25 22:50
The previews in the Electron app vs Chromium are 2 separate implementations.

Not sure what their deployment mag have that breaks them though. Maybe some CSP directives?

**Comment by csett86** [comment] 2021-03-11 20:40
This is an issue of the content security policy (CSP) used in the jitsi instance (not the electron app). I had the same issue on my jitsi instance. If the `img-src` CSP of the used jitsi instance does not contain `data:`, then the error occurs.

You can verify this: With https://meet.jit.si the screensharing previews will work with the electron app.

**Comment by saghul** [comment] 2021-03-11 20:59
Thanks for getting to the bottom of it!

If you feel like it adding some suggestions regarding CSP to the README would be ideal.

I'm closing this since there is nothing actionable for this project.

**Closed by saghul** 2021-03-11 20:59 UTC

**Comment by ubmarco** [comment] 2021-03-12 09:18
@csett86  Wow thanks for that insight, I will forward that to mailbox.org!

**Comment by ubmarco** [comment] 2021-03-12 13:13
They already fixed the server side issue and it works! Thanks a lot again for pinpointing the issue.
