### ISSUE TITLE
2.1.0 breaks video on current stable releases of JM

### ISSUE THREAD

**Issue by C0rn3j** [jitsi/jitsi-meet-electron#352] opened 2020-05-23 23:17 UTC
Issue: client sees their video feed is working, but everyone else sees a black screen for the participant.

```
jitsi-meet 1.0.4074-1
jicofo 1.0_567-2
jitsi-videobridge 2.1_197_g38256192-1
```

* ~~Using 2.1.0 against current stable JM release(versions below) makes camera broken~~ - Fixed in new stable JM release (4627)
  * ~~Using a browser to connect to the same instance works just fine.~~
  * ~~Using 2.1.0 to connect to meet.jit.si works just fine.~~
* ~~Using 2.1.0 P2P sometimes crashes~~ - Worked around in 2.1.1, [chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1086373).
* Using 2.1.0 or Chrome 83 with Experimental Web Platform Features enabled results in sometimes choppy/robotic audio for a participant if they have their video enabled.
* ~~Using 2.1.0 breaks on macOS due to CSP~~ - [workaround](https://github.com/jitsi/jitsi-meet-electron/issues/350#issuecomment-632785610) - Moved to #374

**Comment by Bapf** [comment] 2020-05-25 13:11
Where experiencing this also.
Maybe related to https://github.com/jitsi/jitsi-meet-electron/issues/350 ?

jitsi-meet                              2.0.4548-1
jitsi-meet-prosody                      1.0.4074-1
jitsi-meet-web                          1.0.4074-1
jitsi-meet-web-config                   1.0.4074-1
jitsi-videobridge2                      2.1-197-g38256192-1
prosody                                 0.11.5-1~bionic6

**Comment by seanm** [comment] 2020-05-25 15:31
This sounds a lot like what I'm seeing too.  Downgraded to the 2.0.2 app and things work great again.

**Comment by cedricroijakkers** [comment] 2020-05-26 08:22
I have the exact same problem here. Looking at the other thread, some people are saying that the problem is the Content-Security-Policy headers sent by nginx.

I had a look in the nginx container, but cannot find any CSP header being set there. I also cannot see them being set in the http responses from the server. Looking at what meet.jit.si is sending, there are also no CSP headers there.

I tried starting Jitsi Meet Electron with the `--inspect` switch, and then connecting my Chrome debugger to it, but no interesting logging appears. Is there any way to enable more logging?

**Comment by saghul** [comment] 2020-05-26 08:29
> I tried starting Jitsi Meet Electron with the `--inspect` switch, and then connecting my Chrome debugger to it, but no interesting logging appears. Is there any way to enable more logging?

You can get the source and run it with `npm start` then you have access to the browser console.

**Comment by saghul** [comment] 2020-05-26 08:40
Ok, I've made some progress, and it's worse than I thought. When accessing the current stable on Chrome 83 it just crashes Chrome. Well, the tab. Electron is affected the same way, and when it crashes it shows the white screen.

**Comment by Bapf** [comment] 2020-05-26 09:16
> Ok, I've made some progress, and it's worse than I thought. When accessing the current stable on Chrome 83 it just crashes Chrome. Well, the tab. Electron is affected the same way, and when it crashes it shows the white screen.

Interestingly enough Chrome Version 83.0.4103.61 (Offizieller Build) (64-Bit) works just fine for me both on our installation and on meet.jit.si.

**Comment by saghul** [comment] 2020-05-26 09:51
Do you have "Experimental Web Platform features" turned on? That's needed for E2EE and it's what's causing the crash.

**Comment by saghul** [comment] 2020-05-26 10:07
For reference, this is the bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=1086373 It's private as it's a crash.

**Comment by tiiiecherle** [comment] 2020-05-26 10:14
@saghul Can you release a Version 2.1.1 with all other improvements that 2.1.0 had but disable the "Experimental Web Platform features" and release that as a beta or later when it turns stable?
Thanks

**Comment by Bapf** [comment] 2020-05-26 10:16
> Do you have "Experimental Web Platform features" turned on? That's needed for E2EE and it's what's causing the crash.

Nope, its turned off.
So would it be an option / is it possible to add an advanced setting for that to the client (which is turned off by default)?

**Comment by cedricroijakkers** [comment] 2020-05-26 10:30
Or maybe at least make it a switchable option (if it is possible to change this at run-time in Electron) so we can continue to troubleshoot. The actual E2EE works fine, for audio only of course.

**Comment by saghul** [comment] 2020-05-26 11:51
We can't really add a setting for it since it's required for building the BrowserWindow object.

A new release disabling that is on the cards, but that means that people using meet.jit.si (or running their own deployment off unstable) won't be able to use E2EE which is not nice.

> The actual E2EE works fine, for audio only of course.

Video is fixed, there just hasn't been a stable release since.

I'm trying to figure out what the best course of action is at the moment.

**Comment by cedricroijakkers** [comment] 2020-05-26 12:41
Technically speaking, E2EE is still in beta right? So you could release a 2.1.1 with Electron 9, but with Experimental Web Platform disabled. That would mean that E2EE will be disabled in that release, no matter which version of the server they are running.

At the same time, release a version 2.2.0-rc1 (or similar) with Electron 9 and with EWP enabled. People who want to use E2EE will need to download the 2.2 branch of releases, and people on 2.1 will continue to receive updates with the stable branch. You can tag a release in GitHub to be a pre-release.

You could even go as far as tagging this version 3.0.0, but on the other hand it is backwards compatible, so a major version bump is not correct according to semver standards.

**Comment by Bapf** [comment] 2020-05-26 13:05
First of all: Thx for all your work and your quick response here @saghul 

> Technically speaking, E2EE is still in beta right? So you could release a 2.1.1 with Electron 9, but with Experimental Web Platform disabled. That would mean that E2EE will be disabled in that release, no matter which version of the server they are running.
> 
> At the same time, release a version 2.2.0-rc1 (or similar) with Electron 9 and with EWP enabled. People who want to use E2EE will need to download the 2.2 branch of releases, and people on 2.1 will continue to receive updates with the stable branch. You can tag a release in GitHub to be a pre-release.
> 
> You could even go as far as tagging this version 3.0.0, but on the other hand it is backwards compatible, so a major version bump is not correct according to semver standards.

Sounds reasonable.
Also, the stable release of the client should be in sync with the stable release of the server in my opinion (not with the unstable as it is at the moment). Otherwise you would always need a compatibility-table between client and server. (Which doesn't really work with a client which auto-updates itself).

**Comment by saghul** [comment] 2020-05-26 13:08
> Also, the stable release of the client should be in sync with the stable release of the server in my opinion (not with the unstable as it is at the moment). Otherwise you would always need a compatibility-table between client and server. (Which doesn't really work with a client which auto-updates itself).

That is not the case. Note that the Electron app just loads the client on an iframe. This is a very specific and one-of-a-kind kinda problem, beause it's Chrome 83 (and thus Electron 9) that's broken, not any Jitsii Meet version.

**Comment by awlx** [comment] 2020-05-26 13:32
Did you already see why this is happening with stable so Chrome crashes? We don't have any Jitsi instance to reproduce the crash atm.

**Comment by saghul** [comment] 2020-05-26 13:38
Looks like a timing issue, and somehow latest master must have changed it ever sso slightly not to crash.

**Comment by saghul** [comment] 2020-05-26 14:40
I think I've narrowed it down to H.264 being used by default on P2P calls. For those of you failing. Can you please edit your config.js and set `disableH264` to `true` in the `p2p` section? Did that solve the problem for you? It did on my tests.

**Comment by Bapf** [comment] 2020-05-26 15:26
> I think I've narrowed it down to H.264 being used by default on P2P calls. For those of you failing. Can you please edit your config.js and set `disableH264` to `true` in the `p2p` section? Did that solve the problem for you? It did on my tests.

I can test later (since the server is in use at the moment and I don't want to fiddle with it now).
But just for my understanding: I already have set `enabled: false,` in the `p2p` section, so I thought changing anything else there wont have any effect. Am I mistaken there?

**Comment by seanm** [comment] 2020-05-26 15:32
My scenario is just like @Bapf : I already have p2p off, and saw the issue with a 16 person group session.  I can toggle the disableH264 anyway this evening, after the work day.

**Comment by C0rn3j** [comment] 2020-05-26 15:34
I think things are getting confusing by the fact that there are two issues being discussed - 2.1.0 crashing due to a bug in Chromium and 2.1.0 having broken video on stable release.

The latter is probably fixed by the new release that got tagged an hour ago .

https://github.com/jitsi/jitsi-videobridge/releases/tag/stable%2Fjitsi-meet_4627
https://github.com/jitsi/jicofo/releases/tag/stable/jitsi-meet_4627
https://github.com/jitsi/jitsi-meet/releases/tag/stable/jitsi-meet_4627

**Comment by saghul** [comment] 2020-05-26 15:43
> But just for my understanding: I already have set `enabled: false,` in the `p2p` section, so I thought changing anything else there wont have any effect. Am I mistaken here?

No, that's correct. If you have p2p disabled (why would you though?) then this doesn't apply to you.



> And we had the issue (black video for one participant while he can see himself just fine) not only in 1-to-1 calls but also in group calls.

This is due to a bug in our use of insertable streams. We just pushed a new stable release (Docker coming tonight) which fixes that.

**Comment by saghul** [comment] 2020-05-26 15:43
> The latter is probably fixed by a new release that got tagged an hour ago.

Correct!

**Comment by Bapf** [comment] 2020-05-26 15:58
> No, that's correct. If you have p2p disabled (why would you though?) then this doesn't apply to you.

For data-privacy-reasons. We use jitsi meet (among other things) for student application interviews and for this usecase we have the order that no external server should be involved in the process. And since we don't have own stun servers we disabled p2p.

> This is due to a bug in our use of insertable streams. We just pushed a new stable release (Docker coming tonight) which fixes that.

Ok. Just seen it and will update later.
(Again: thx for your great work!)

**Comment by C0rn3j** [comment] 2020-05-26 19:11
I updated my instance to the new stable, and the issue described in my initial message is there again.

>Using 2.1.0 to connect to a git release JM works, but if a participant has video turned on, the audio becomes extremely choppy. (maybe not limited to the electron client, did not test with browser)

Turns out it is limited to the electron client, as browser works, and so far only happens for one specific participant using 2.1.0 on W10 1909.

For another participant on 2.1.0 on W10 1903 the call works fine as long as it's not P2P. The moment the call switches to P2P (1 on 1), the client crashes for them.

I'm using 2.1.0 on Arch Linux (extracted from the .AppImage) and it works fine for me.

**Comment by saghul** [comment] 2020-05-26 20:09
That's... weird. If the problem was related to insertable streams, you should have gotten it regardless of the operating system.

**Comment by saghul** [comment] 2020-05-27 09:45
2.1.1 is out which fixes the crash. @C0rn3j this may fix your problems too, since they where H.264 related, and the HW codec ~~is~~ was used there.

**Comment by cedricroijakkers** [comment] 2020-05-27 09:53
I have updated to 2.1.1, FYI I'm running on Ubuntu 20.04:

- Video camera now works, I can see myself and all other participants can see me too
- Desktop sharing still doesn't work, I see my desktop but everyone else sees nothing or a frozen camera

**Comment by saghul** [comment] 2020-05-27 10:01
>     * Desktop sharing still doesn't work, I see my desktop but everyone else sees nothing or a frozen camera

I cannot reproduce this. Any chance you are running macOS Catalina and you haven't granted the screen sharing permission in the system settings?

**Comment by cedricroijakkers** [comment] 2020-05-27 10:06
I'm running Linux, so no, that's not the problem here. I'm cloning the code now and going to run it with npm, see if I can get some more logging out of it. Other participants see the little icon that I am trying to share a screen, but they don't see the actual screen.

**Comment by cedricroijakkers** [comment] 2020-05-27 10:12
That doesn't show me anything more, in master it also doesn't work.
I get this in the console, but I'm not sure it is related:

[1] [133269:0527/120735.278089:ERROR:webrtc_video_engine.cc(3252)] Absent receive stream; ignoring clearing encoded frame sink for ssrc 0

**Comment by C0rn3j** [comment] 2020-05-27 10:25
> 2.1.1 is out which fixes the crash. @C0rn3j this may fix your problems too, since they where H.264 related, and the HW codec ~is~ was used there.

That does indeed fix the P2P crash, but I don't think it fixes the choppy audio, since that happened with 3 people too.

**Comment by cedricroijakkers** [comment] 2020-05-27 11:17
Update from my part:

The following combination works with video *and* screen sharing:

- Jitsi meet electron: 2.1.1
- Jitsi meet docker containers: stable-4627-1

**Comment by saghul** [comment] 2020-05-27 11:33
> I don't think it fixes the choppy audio, since that happened with 3 people too, can't test that atm.

There is really nothing we can do on the Electron app for that. If you can reproduce with Chromium 83 please open an issue on jitsi-meet, since it might be related to the video bridge.

**Comment by C0rn3j** [comment] 2020-05-27 17:30
> > I don't think it fixes the choppy audio, since that happened with 3 people too, can't test that atm.
> 
> There is really nothing we can do on the Electron app for that. If you can reproduce with Chromium 83 please open an issue on jitsi-meet, since it might be related to the video bridge.

Just tested with both 81 and 83 Chrome. (Unless you really meant Chromium specifically - if so, are there Windows links for prebuilt binaries?)

Version 81.0.4044.138 (Official Build) (64-bit)
Version 83.0.4103.61 (Official Build) (64-bit)

These versions both work fine, JME 2.1.0 and 2.1.1 do not.
Turns out the issue only happens in 3+ person calls, 1on1 calls work just fine.

Also for some reason the browser ends up having a higher camera framerate than the desktop client (from about 15 to 30 FPS)

**Comment by saghul** [comment] 2020-05-27 20:48
Thanks for the thorough testing!

> Unless you really meant Chromium specifically - if so, are there Windows links for prebuilt binaries?

No, for the purpose of this test they should be equivalent.

> These versions both work fine, JME 2.1.0 and 2.1.1 do not.

2.1 is when we updated to Electron 9, which uses Chrome 83 as the engine...

I have a hunch. Test this. On Chrome 83, go to chrome://flags and enable "Experimental Web Platform Features" then repeat the test. Do you get comparable results to JME 2.1.X ?

**Comment by tiiiecherle** [comment] 2020-05-28 07:27
I don't know if this is related somehow. I know that @C0rn3j is building the packages himself on archlinux like me.

The latest stable build contains the following error:

```
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.1/linux-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.1/linux-x64-83_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
```

It is not a nom error. The file
`https://github.com/sass/node-sass/releases/download/v4.13.1/linux-x64-83_binding.node`
really just does not exist.

After that the build continues without downloading more sources. Perhaps parts of the package are missing then and it is not working correctly.

I tried building with the latest git sources. The build succeeds without the error above. I did not have a chance to test the latest electron version yet. And I did not file another issue on jitsi-meet about that. Please let me know if necessary.

@saghul 
Please do another stable jitsi-meet release as the latest jitsi-meet_2.0.4627 contains the following error when building own packages.

I will also try the latest JME after a new stable jitsi-meet release.

Thanks

**Comment by C0rn3j** [comment] 2020-05-28 07:56
>I don't know if this is related somehow. I know that @C0rn3j is building the packages himself on archlinux like me.
I'm using the -bin package which just extracts the .AppImage

node-sass has 4.13.1 which the highest number after the dash is 79 - `linux-x64-79_binding.node`

4.14.1 has `linux-x64-83_binding.node`

**Comment by saghul** [comment] 2020-05-28 08:04
> I don't know if this is related somehow. I know that @C0rn3j is building the packages himself on archlinux like me.
> 
> The latest stable build contains the following error:

Not related in any way, that's a different project even :-)

What Node version are you using? That number is the Node ABI.

At any rate, all of that is off-topic here.

**Comment by C0rn3j** [comment] 2020-05-28 14:17
> Thanks for the thorough testing!
> 
> > Unless you really meant Chromium specifically - if so, are there Windows links for prebuilt binaries?
> 
> No, for the purpose of this test they should be equivalent.
> 
> > These versions both work fine, JME 2.1.0 and 2.1.1 do not.
> 
> 2.1 is when we updated to Electron 9, which uses Chrome 83 as the engine...
> 
> I have a hunch. Test this. On Chrome 83, go to chrome://flags and enable "Experimental Web Platform Features" then repeat the test. Do you get comparable results to JME 2.1.X ?

Chrome 83 EWPF disabled - All works great
Chrome 83 EWPF enabled - P2P crashes, light and infrequent audio distortion
JM 2.1.1                              - Light and infrequent audio distortion

I guess the audio issues aren't as bad as last time for some reason (better connection of the participant?) but yes, it does confirm your theory that enabling that flag is the cause of the audio issues.

**Comment by seanm** [comment] 2020-05-28 14:50
I'm seeing much like @C0rn3j right now (am currently in a meeting). Just tried JitsiMeetElectron 2.1.1 and audio often becomes robotic and stuttery, went back to 2.0.2 and audio is great, went back to 2.1.1 and audio is choppy again.

**Comment by tiiiecherle** [comment] 2020-05-30 13:24
Issue [#350](https://github.com/jitsi/jitsi-meet-electron/issues/350) was closed in favor of this one. But even with the latest JME version only a very insecure version of `add_header Content-Security-Policy` works.

It is still the problem described [here](https://github.com/jitsi/jitsi-meet-electron/issues/350#issuecomment-632785610).

Has anyone found a safer setting that works with the latest JME?

@saghul Would you prefer to reopen the old issue, file a new one or discuss it here as the other issue was closed in favor of this one?

Thanks for anyone that can help out with that. Have a nice weekend ;)

**Comment by saghul** [comment] 2020-05-30 20:21
@tiiiecherle Can you please open a new one, being explicit about CSP?

Note that there is likely nothing we can do other than document the header combo that works, once we find it.

**Comment by saghul** [comment] 2020-05-30 20:24
@C0rn3j @seanm This does confirm that insertable streams ( what’s used for E2EE) might be the culprit.

The API is such that even when E2EE is not used, the frames are piped through an empty transform. There is no way to turn on insertable streams “on the fly”, you have to always have them enabled.

We’ll look into this and create issues in the Chromium bug tracker as necessary. Thanks for the help!

**Comment by Echolon** [comment] 2020-06-02 20:21
@C0rn3j @saghul 

Would it make sense to condense the remaining point into a new issue?

**Comment by Echolon** [comment] 2020-06-03 12:06
@C0rn3j may you can put those checkmarks from markdown


- [X] Using 2.1.0 against current stable JM release(versions below) makes camera broken - Fixed in new stable JM release (4627)
- [X] Using a browser to connect to the same instance works just fine.
- [X] Using 2.1.0 to connect to meet.jit.si works just fine.
- [X] Using 2.1.0 P2P sometimes crashes - Worked around in 2.1.1, chromium bug.
- [ ] Using 2.1.0 or Chrome 83 with Experimental Web Platform Features enabled results in sometimes choppy/robotic audio for a participant if they have their video enabled.
- [X] Using 2.1.0 breaks on macOS due to CSP - workaround - Moved to #374

**Comment by saghul** [comment] 2020-06-10 07:16
Agreed @Echolon. There is not much we can do from our side, other than wait for a Chrome update. I did pass this feedback to Google, FWIW.

**Closed by saghul** 2020-06-10 07:16 UTC

**Comment by C0rn3j** [comment] 2020-06-10 09:33
@saghul Is there a thread I can follow about the remaining audio issue, now that this thread is closed?

Am assuming there's a bug report on Chromium tracker about it?
