### ISSUE TITLE
High CPU load (Linux)

### ISSUE THREAD

**Issue by k0a1a** [jitsi/jitsi-meet-electron#259] opened 2020-04-10 21:55 UTC
Hi,
first of all thanks for your great work. I'm able to use the client reliably for 3-4 participants calls on a selfhosted network of multiple Jitsi-meet/videobridge hosts and it's working great.

There is, however a need for running 20+ participants calls which isn't working. The bottleneck is quite clearly in the messy implementation of hardware video decoding in Chromium/Electron (and Firefox) on Linux (Debian 10 / Ubuntu 18.04) which seem to default to software decoding causing very high CPU load.

I have a standalone Chromium v81 which reports hw decoding as enabled (see below) and indeed I can watch 1080p 60fps YouTube videos with CPU load at about 10-15%.

Similarly, a 720p video call with two participants (non p2p) causes about 10% CPU load on my system with i5-8350U CPU (Intel UHD graphics)

Each new participant joining the call, seems to increase the CPU load by about 10%.

Looking at __top -c__ it appears that '--type=renderer' thread of Electron/Chromium is causing most of the load.

I'm not familiar enough with Electron internals to determine if 'renderer' thread isn't making use of hardware decoding or something else is off.

Is there a specification as to which H264/VP8/VP9 encoding profiles are used in Jitsi video streams?

According to __vainfo__ hardware decoding is available and Chromium v81 seems to be making use of it:

![79020059-1b262c80-7b78-11ea-8a71-4e78b02ad1ba](https://user-images.githubusercontent.com/876449/79025444-06e92c00-7b86-11ea-9e7f-2ddb27c6654e.png)

![79020051-1497b500-7b78-11ea-90f0-313197e423d7](https://user-images.githubusercontent.com/876449/79025450-0ea8d080-7b86-11ea-82d2-af3344c45dec.png)

Thank you,

**Comment by genodeftest** [comment] 2020-04-17 11:23
I cannot confirm this issue on a very old computer (way slower intel CPU/GPU than you have). In my case, the renderer runs at 9% permanently. I've tested with 2.0.2. Can you please try that version too?

**Comment by ekianjo** [comment] 2020-05-26 14:28
This also happens with the latest version 2.1.0 so far... even with 3 video participants. (on Linux at least)

**Comment by maik-s** [comment] 2020-05-27 10:05
I can confirm that jitsi meet electron (2.1.0) consumes very high cpu usage on my Windows (1909) system, when someone from the chat (not necessarily me) shares the sceen.

**Comment by Glutexo** [comment] 2020-12-08 16:24
macOS version also seems unaccelerated. Running the same meet in Safari consumes much less resources than in this app.

**Comment by saghul** [comment] 2020-12-08 16:36
All of them are as of current master, btw. HW acceleration seems to create flickering in screen-sharing. You can check in chrome://gpu what codecs are HW accelerated in Chrome. VPX isn't on my machine.

**Comment by saghul** [comment] 2021-03-04 09:07
GPU has been enabled again as of 2.6.0. Since there is nothing actionable on the Electron side, I'm closing this is in favor of https://github.com/jitsi/jitsi-meet/issues/5816

**Closed by saghul** 2021-03-04 09:07 UTC
Labels: GNU/Linux
