### ISSUE TITLE
Invalid Server URL

### ISSUE THREAD

**Issue by weaktyper** [jitsi/jitsi-meet-electron#109] opened 2018-08-16 20:06 UTC
Hi,

I'm seeing `Invalid Server URL`. The url works fine from a browser but not from this project.
The jitsi server was created with `https://github.com/jitsi/docker-jitsi-meet`

Not sure what the issue is?

**Comment by saghul** [comment] 2018-08-17 08:42
The problem is the docker image is not allowing access to the external API, I'm fixing that now, thanks for the report!

**Comment by saghul** [comment] 2018-08-17 09:03
This is fixed in the latest Docker containers. Here is the fix: https://github.com/jitsi/docker-jitsi-meet/commit/0bc1a8b49cdbe9c175508dd643543f017e563570

Note that you need to delete your config directory so the new default files are copied in. Cheers!

**Closed by saghul** 2018-08-17 09:03 UTC

**Comment by weaktyper** [comment] 2018-08-17 13:47
I was about to make that change to the `nginx.conf`

I have a number of suggestions for the docker repo. If I get time, I will open issues over there.

For one thing, the lack of tagged versions for the images I would class as high priority to be changed.

**Comment by weaktyper** [comment] 2018-08-17 13:47
Thanks @saghul

**Comment by saghul** [comment] 2018-08-17 14:00
> I have a number of suggestions for the docker repo. If I get time, I will open issues over there.

Please do!

> For one thing, the lack of tagged versions for the images I would class as high priority to be changed.

Good idea. I briefly considered it, but I want to wait a bit until the images mature...
