### ISSUE TITLE
2022.6.1 ends meeting with no way to start a new meeting except to quit-and-relaunch

### ISSUE THREAD

**Issue by TallTed** [jitsi/jitsi-meet-electron#763] opened 2022-06-27 19:46 UTC
## Description

Leave a meeting in **Jitsi Meet.app** 2022.6.1.  Note advertising for integrating Jitsi elsewhere, but no way to join a new meeting.  Quit and relaunch to join a new meeting.

## Current behavior

Leave a meeting in **Jitsi Meet.app** 2022.6.1.  Note advertising for integrating Jitsi elsewhere, but no way to join a new meeting.  Quit and relaunch to join a new meeting.

## Expected Behavior

Leave a meeting in **Jitsi Meet.app** 2022.6.1.  Have a way to join a new meeting without quit-and-relaunch.

## Possible Solution

Leave a meeting in **Jitsi Meet.app** 2022.6.1.  Have a way to join a new meeting without quit-and-relaunch.

## Steps to reproduce

Leave a meeting in **Jitsi Meet.app** 2022.6.1.  Note advertising for integrating Jitsi elsewhere, but no way to join a new meeting.  Quit and relaunch to join a new meeting.

## Environment details

macOS High Sierra 10.13.6 (17G14042) on MacBook Pro (Retina, 15-inch, Mid 2015)

**Comment by saghul** [comment] 2022-06-27 20:57
This should also be happening with the current version is it not?

We had a bug on the meet.jit.si deployment which lacks the close button in some close meeting screens. We have fixed it and will be part of the next update. The Electron app will pick it up since it's part of the content it dynamically loads.

Sorry about that.

**Comment by TallTed** [comment] 2022-06-28 13:48
Having tested with a manually downgraded 2022.4.1, yes, this issue is now seen in that version as well (which it was not last week, when I last attended a meeting using 2022.4.1, leading me to think it was the upgrade to 2022.6.1 that caused it).  The fix cannot come soon enough.

**Comment by csett86** [comment] 2022-07-02 21:00
This is a duplicate of #757, thus closing here

**Closed by csett86** 2022-07-02 21:00 UTC
