### ISSUE TITLE
Checking for update, Trace/breakpoint trap

### ISSUE THREAD

**Issue by probonopd** [jitsi/jitsi-meet-electron#513] opened 2021-02-06 07:35 UTC
```
me@host:~$ /isodevice/Applications/jitsi-meet-x86_64.AppImage 
08:33:52.405 › Checking for update
Trace/breakpoint trap

me@host:~$ uname -a
Linux host 5.3.0-28-generic #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Is there an argument that can be used at runtime to turn off the update check?

**Comment by saghul** [comment] 2021-02-09 10:26
Not at the moment, but I doubt that is the cause of the problem. Can you get a core dump and paste the packtrace?

**Comment by csett86** [comment] 2022-07-24 13:25
Closing as unable to reproduce

**Closed by csett86** 2022-07-24 13:25 UTC
